const interestOptions = [
  { value: "reading", label: "Reading" },
  { value: "writing", label: "Writing" },
  { value: "painting", label: "Painting" },
  { value: "drawing", label: "Drawing" },
  { value: "photography", label: "Photography" },
  { value: "traveling", label: "Traveling" },
  { value: "hiking", label: "Hiking" },
  { value: "cycling", label: "Cycling" },
  { value: "running", label: "Running" },
  { value: "yoga", label: "Yoga" },
  { value: "meditation", label: "Meditation" },
  { value: "gardening", label: "Gardening" },
  { value: "cooking", label: "Cooking" },
  { value: "baking", label: "Baking" },
  { value: "gaming", label: "Gaming" },
  { value: "playing_music", label: "Playing Music" },
  { value: "listening_to_music", label: "Listening to Music" },
  { value: "watching_movies", label: "Watching Movies" },
  { value: "watching_tv_shows", label: "Watching TV Shows" },
  { value: "knitting", label: "Knitting" },
  { value: "sewing", label: "Sewing" },
  { value: "crocheting", label: "Crocheting" },
  { value: "dancing", label: "Dancing" },
  { value: "singing", label: "Singing" },
  { value: "acting", label: "Acting" },
  { value: "learning_languages", label: "Learning Languages" },
  { value: "bird_watching", label: "Bird Watching" },
  { value: "fishing", label: "Fishing" },
  { value: "camping", label: "Camping" },
  { value: "surfing", label: "Surfing" },
  { value: "skateboarding", label: "Skateboarding" },
  { value: "snowboarding", label: "Snowboarding" },
  { value: "skiing", label: "Skiing" },
  { value: "scuba_diving", label: "Scuba Diving" },
  { value: "snorkeling", label: "Snorkeling" },
  { value: "playing_chess", label: "Playing Chess" },
  { value: "playing_board_games", label: "Playing Board Games" },
  { value: "solving_puzzles", label: "Solving Puzzles" },
  { value: "woodworking", label: "Woodworking" },
  { value: "metalworking", label: "Metalworking" },
  { value: "collecting", label: "Collecting" },
  { value: "stamp_collecting", label: "Stamp Collecting" },
  { value: "coin_collecting", label: "Coin Collecting" },
  { value: "video_editing", label: "Video Editing" },
  { value: "blogging", label: "Blogging" },
  { value: "vlogging", label: "Vlogging" },
  { value: "podcasting", label: "Podcasting" },
  { value: "drawing_comics", label: "Drawing Comics" },
  { value: "writing_poetry", label: "Writing Poetry" },
  { value: "creative_writing", label: "Creative Writing" },
  { value: "photography_editing", label: "Photography Editing" },
  { value: "makeup_artistry", label: "Makeup Artistry" },
  { value: "nail_art", label: "Nail Art" },
  { value: "fashion_design", label: "Fashion Design" },
  { value: "interior_design", label: "Interior Design" },
  { value: "graphic_design", label: "Graphic Design" },
  { value: "web_design", label: "Web Design" },
  { value: "fitness_training", label: "Fitness Training" },
  { value: "bodybuilding", label: "Bodybuilding" },
  { value: "martial_arts", label: "Martial Arts" },
  { value: "kickboxing", label: "Kickboxing" },
  { value: "boxing", label: "Boxing" },
  { value: "archery", label: "Archery" },
  { value: "horseback_riding", label: "Horseback Riding" },
  { value: "tennis", label: "Tennis" },
  { value: "badminton", label: "Badminton" },
  { value: "soccer", label: "Soccer" },
  { value: "basketball", label: "Basketball" },
  { value: "volleyball", label: "Volleyball" },
  { value: "cricket", label: "Cricket" },
  { value: "rugby", label: "Rugby" },
  { value: "baseball", label: "Baseball" },
  { value: "american_football", label: "American Football" },
  { value: "hockey", label: "Hockey" },
  { value: "table_tennis", label: "Table Tennis" },
  { value: "squash", label: "Squash" },
  { value: "golf", label: "Golf" },
  { value: "bowling", label: "Bowling" },
  { value: "cycling_touring", label: "Cycling Touring" },
  { value: "rock_climbing", label: "Rock Climbing" },
  { value: "mountain_biking", label: "Mountain Biking" },
  { value: "kayaking", label: "Kayaking" },
  { value: "canoeing", label: "Canoeing" },
  { value: "fencing", label: "Fencing" },
  { value: "esports", label: "Esports" },
  { value: "programming", label: "Programming" },
  { value: "robotics", label: "Robotics" },
  { value: "astronomy", label: "Astronomy" },
  { value: "science_experiments", label: "Science Experiments" },
  { value: "diy_projects", label: "DIY Projects" },
  { value: "volunteering", label: "Volunteering" },
  { value: "community_service", label: "Community Service" },
  { value: "event_planning", label: "Event Planning" }
];

export default interestOptions;
